sudo: false
language: python
services:
- mysql
python:
- '2.7'
env:
  matrix:
  - DB=sqlite3
install:
- pip install -r requirements.txt
before_script:
- pip install coverage
- pip install python-coveralls
- pip install pep8
- cp travis-ci/manage.py manage.py
- python manage.py migrate
script:
- pep8 hx_toolkit/ --exclude=hx_toolkit/migrations
- FORCE_VIEW_TESTS=1 coverage run --source=hx_toolkit/ --omit=hx_toolkit/migrations/*
  manage.py test hx_toolkit
after_script:
- coveralls --merge=js-coverage.json
before_deploy:
- find hx_toolkit/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > hx_toolkit/VERSION
deploy:
  provider: pypi
  user: uw-it-axdd
  skip_cleanup: true
  password:
    secure: UMNHhsgTds1bj1ITSpXbUGReyLy9gRjW73VWgBqkzwD2Gx2vOc1PGC7UyeeAmiMKKr1+QQCdeecDxm7tAunPdaNEWpTKCG/3TZm/MkTtqa+x6N+jXj8OgzVkoo8w20Bmu1+xEGq/svqtU09aBbjF/JWx+i7qBrGr+K/38SibMiJSEJPSY7DrYRuqk0KyM5UO9Z1KY0hv47Bq+97vPeSvYWVqNl2IjrtLQCCnnbFeuYDmRIfm/Qgj89wW5w5Hx+dwiNqDwmQbCcX4v3mZGq5bmK4wM4jx5req+4moCJZYQ9MaQSo1tvCZA8GarGg9L8LOjXTXDaEImi7UqP9nUSjZNzxsaiBwSs9iV/isl9EQzKub4yror/I4x3R1+3C4yhtXI8DBbO9r1wdxQsUUor19Hq6VIsd1Og1biseY4sblaC5Z4fZYJ7ai9grJOVx0ctZADu3OE9S+s2mLJVY8QjNFa8vKNeVpOgdPGbd7jDDNIvQJYWPwcGXvye2/f/pY14U/C/haxBvh2SVI8XqoFVUzkH9KvhBcKO1c8L2XbfNdIb67stX1aS7lEYxdgd2c1tN+DJ7DUj+M9/2f9QNmu5uwTkYP7QziLhBhscR7TwtJszPp9xnyJBVN8xas6uZP6f+ySJeF7X7IijxhTEoT+yDrCpov66MMkcQ9ycNxz0u32bQ=
  on:
    tags: true
    python: '2.7'
