sudo: false
language: python
services:
- mysql
python:
- '2.7'
env:
  matrix:
  - DB=sqlite3
install:
- pip install -r requirements.txt
before_script:
- pip install coverage
- pip install python-coveralls
- pip install pep8
- cp travis-ci/manage.py manage.py
- python manage.py migrate
script:
- pep8 hx_toolkit/ --exclude=hx_toolkit/migrations
- FORCE_VIEW_TESTS=1 coverage run --source=hx_toolkit/ --omit=hx_toolkit/migrations/*
  manage.py test hx_toolkit
after_script:
- coveralls --merge=js-coverage.json
before_deploy:
- find hx_toolkit/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > hx_toolkit/VERSION
deploy:
  provider: pypi
  user: uw-it-axdd
  skip_cleanup: true
  password:
    secure: UcakBsLIn+YFI75p2VSORMGDzqlA6hi0JiTy5nOMOcxNAXDF3rfkH3iC9bml5/BcAPxsTjs0rpJ2VpzLzIeYjZb7fIUpD8fPpLWdMyQDV5Qna2mNbl0EhfdAJUROJZCtY1AZZ612GcrtcC7I9Z3p1fx3g2Gju3rnaipxNNLtsPzE/wtPbe895KkWEzZB/0ObdeKYobEZj9qAGuVbaMwZeIWGMFJHUoE5ljYPlELQvLou4Mc2fwXM9f0U8jDTw1sfIJoNrA/DBRmoe3nFtJJCoj43N06Pa5pv9mTW9CXmLz+Boi6aHt/zV/4kL04WwEzQaixLJstMvtsi6ovXGH/AvfgMooQvDvQj7lWRUKbUOxF/EF5vOoRKx0Cx3E2auV91aH+DUDB6I/QUyBnopHzWx5mWhUWyxHhV3h3MlbY+ukWVZnLGQRBRdp4+Bo0BQrj4mfmBxxF/z2+bXliirwFIokR2Ux8kNAlm6wugewp5B5UGdPulVoGRT+lR87CWtmviVWsyQN3qE6R927jSxeo2vvsD1YDbqT0HN2xVTCmdXE1mYRZ73EkPxHalJnRb1rrH20cWyNgKkVs6yzg62gZzfxPGFb2luHvd+QldUEzFh/L6ZDa4DX6n+8JDWEmiS0t0I4c8meEod767BAZwVdiVXSfIzh42/3HpFpz8Iw8plOI=
  on:
    tags: true
    python: '2.7'
