sudo: false
language: python
services:
- mysql
python:
- '2.7'
env:
  matrix:
  - DB=sqlite3
install:
- pip install -r requirements.txt
before_script:
- pip install coverage
- pip install python-coveralls
- pip install pep8
- pip install nose2
- cp travis-ci/manage.py manage.py
- python manage.py migrate
script:
- pep8 interview_db/ --exclude=interview_db/migrations
- FORCE_VIEW_TESTS=1 coverage run --source=interview_db/ --omit=interview_db/migrations/*
  manage.py test interview_db
after_script:
- coveralls
