language: python
python: 3.6
services: docker
os: linux
env:
  global:
    - RELEASE_NAME="interview-db"
    - DJANGO_APP="interview_db"
    - COMMIT_HASH="$(git rev-parse --short=7 HEAD)"
    - IMAGE_TAG="${RELEASE_NAME}:${COMMIT_HASH}"
    - secure: "Yz/dIz3oqT4a3dik6ZFmTUBS62NhXk+uWOXawppvf/ObRvrQgLovFk+7JaPjoMDPFch4MP7eiWDloNM9ahHRLx6trqWmSaTGKD7iWZ+bc3PaQbc0hQoBT9oC3cRM3kM01WdgjYRJ7QLHeCDeEX/ug3JD1gMHm9RGIKKiA9cpz9Ff9XXZn70KR2SET30cgXmL3hDl4mTcVfZWFGSwUn806LTrz6W5nPnxnEC33towsQ5nPvImQyn/ECiDxk2PxTjt89GoGzRaBx9+0jdjzNGu6J2p00TXITTiS+9Q2gaZNAVKYLJqw9neH5PEKlYD4CMIT3d9j7focIWQ2lxO/4w89lQB//0f2Dx2z5PCiZcxrjuiWENF+4tXqexNFZd3kHuPNxscWg8wuTo2i2uxlicqVWBW4FIx2giDCXVgzquz8lkNHtizZwcdk9d59wzfHhgdVllxBmYq1dFqYmSsmxI8T9zWnAmAaScSMgZ+4V0dnfxbsgAnP16+m8qf0WCTMg+XY/mBL0ddOOI/Qp8iy8Zc8ejYv86aVHytAJgttkccBU2BK7/aJ/WMjlrE/NZZPAtJzxvk3Hd3b5TtATIqrwlm7/6sjdJyu0cxbm2wFsKanH+EJD9I8Xu1W+AT+BDZtPxA6PnjWV0eapFFsppZyJb5QNBuPbfKgS9q36iuRPJUqRo="
    - secure: "L4KlehCucZLJLcxEgNHVUqf/2wU+3HGMJI7mOimctG0U/W1zrgwiKPpkQZlCRanumNzwZl8AgjQ7K147LqKL3DUeiWjjyIYqBH5M/lg/YopU81LobL59vzbCR2ker3Yrx/sZnc73blwWXhEmqHU/HYmTAYhUlqsOb7wdmJOTJa/yg7+YgEpYOAT4na3atGziiSqfet3IocpxLeTs85hJ4JRiw+rKfGUDNpdptw+9+q85KUcUpfw+zE5de3gbPZKhuUdTsoaxqo+aolTr0imjC654iDTZdRIh297OxQu+WpsopRdTO55EUuaVee/mtZaWZ8ZpYDRBtCb5YGUEJgTk6TCyjv0suPVjUPH2DF8wJT08zIwIq3SvqFk0/B4LpMD8Ig2wGMioBtr8CIv0tAqP8RxNEy3oHwPdbm57qO515x2PM+JZuiTjLoqMyn1DtViWFJGH/Io4/nreUSqECvsDXGHzzKFN/EGbu2ilqOw4JppXiHyFbynWerUinHbuXiOZsumyHj5N8ZQPDyGr5LgpWBIQVs9T3M3OcmeKnKmDGhYf2i+P0pa9Mz38nabiL/pmnCThonG7xKVLAW+sHzhOj3l3E9WngT0/PtnD094GyO57joIVyxhFXk+di8CH7uQvl7uh8v7MOZmUrmF99UIxtjbQGy9kY1yBjsDjx1zJ55g="
    - secure: "DC6EFmLGr9Y743mYMYWUOBwbLdwfEQ+k32zlA/BzArPxJdCKfbENfDrNwLDOAJ9/0GCsMaA8v1xFA86RVmAIIRdx+B8tAIxY/muhEO19YqDvHfURPRIkYtkpSSM32fWvcSx11Db3BPxCa+9ynr7G6L3JVZAVsVRTtfVdY4ejwgMUXpw1anH2EfRuTdQ93i5Z+Z53ZQK9OSGRVHO6x+RrJWMuDS/N3sz/gmG5gMxc8q8F/Gri7/+dCzVLg5rU5Rl00qLWT4Yg7Xuf8nuIfDTn3+KLpnnM/JeNH6NVGRL4DqOpy/Q9O1QJidIvkqE8OP07AYWINLopEIYgJbLpHsqtJxO0FnWp1Vpr0B/3B2a1dcp6pXReO73ax2V8DD83R50etJtXbPveu+2kAJeZlp4lejO82lGso2oyt70dsBzYg9702ekNmgVAJxt4Q1aeh/9/utstvvPfXVghq/HQ3Klos3UvJdaNwKeKuXYZPoxSoexXYw0bsIxr/ZZkGb6xD79uAk98u7w8WsBC4dgKv5uP0UbgA2zyUNhrMvqCltcEKgzBNMpLtuWX3c8iS3yzKwBQvbLS9Wws768UFxY6jMA7/gT3Cmu74odGIZtVR6/WFDIfPxC5QBPYeJCwHDxD7bnuyhJ9AiM1eY0xDAHfwt6OmkPtX3G7UEwK0UQgjxfM7pw="
jobs:
  include:
    - stage: compile
      script: docker build -t "$IMAGE_TAG" .
    - stage: test
      install: 
        - pip install coverage
        - pip install coveralls
      script: echo "no tests!"
      after_success:
        - cp /tmp/.coverage.* .
        - coverage combine
        - coveralls
    - stage: deploy
      if: branch =~ /^(develop|master)$/ AND type != pull_request
      script: curl -Ls https://raw.githubusercontent.com/uw-it-aca/gcp-app-deploy/master/travis-ci/deploy.sh | bash
cache:
  directories:
  - "$HOME/helm"
  - "$HOME/kubeval"
