sudo: false
language: python
services:
- mysql
python:
- '2.7'
env:
  matrix:
  - DB=sqlite3
install:
- pip install -r requirements.txt
before_script:
- pip install coverage
- pip install python-coveralls
- pip install pep8
- cp travis-ci/manage.py manage.py
- python manage.py migrate
script:
- pep8 hx_toolkit/ --exclude=hx_toolkit/migrations
- FORCE_VIEW_TESTS=1 coverage run --source=hx_toolkit/ --omit=hx_toolkit/migrations/*
  manage.py test hx_toolkit
after_script:
- coveralls --merge=js-coverage.json
before_deploy:
- find hx_toolkit/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > hx_toolkit/VERSION
deploy:
  provider: pypi
  user: uw-it-axdd
  skip_cleanup: true
  password:
    secure: B90FN93keemcjWBuGeUPh89KgKwyDsGJCYZwlmsv7RavUL/+BaVhymIe2qqCOsi7btIBUeTlsd71DyZsPiNcXY872wrBqTidFCS18tz2uxB0LDWF9BRWwTBfHZh7ZzRDmUgtz9eN5FL9aS621upNyYCNzr1VpLlVcX0QfbXgUd30KBMiWW+9IQwfubEScW+YqlvO9u9xhVDATIIb1Uf2WUSrWq7RLMPRJAcX0xVZUro3CpOlhL1ZNipTEpc+WYG4VuO4ZC8/Epxv+mEyq1tXLicI1xhzPtWSA/uDMOuHn/GmtZjggpeWFZwlaYL45jVjZYladeJgQ4JLXINaExZqRhDqk+zodyZOR0fA4lO0wAyeiXWDoqjrQD0Fn5dYqJvOUSaZ+GVlHayOJeABH2Ob+Lvp58Eu0XqQTPeBLsrCcux+KwUErTnCpdPxoRY3VAB0YDhsUbO3VfOijVvkFu6tx6IrsqrI/saVaRPLHmnvb1RwpxfTk8FdkyMfvaHmxHmDcDDWnt1DZ+3NdcsuYVrwXpj2XRekk5n06p2+CW1U+EwS7ocpL2dBfT1bGMKm0PfaEeEv9wHQ8Ep0JV7FZ9bTkIA2EYFvp5USmMqf+9jXCJ8QfkyyTxoFRYGswZGSDHCNvDhWLLMzka3cTOLd0WQTbGpLg3zxms3CINmSSAYOOUA=
  on:
    tags: true
    python: '2.7'
