sudo: false
language: python
services:
- mysql
python:
- '2.7'
env:
  matrix:
  - DB=sqlite3
install:
- pip install -r requirements.txt
before_script:
- pip install coverage
- pip install python-coveralls
- pip install pep8
- cp travis-ci/manage.py manage.py
- python manage.py migrate
script:
- pep8 hx_toolkit/ --exclude=hx_toolkit/migrations
- FORCE_VIEW_TESTS=1 coverage run --source=hx_toolkit/ --omit=hx_toolkit/migrations/*
  manage.py test hx_toolkit
after_script:
- coveralls --merge=js-coverage.json
before_deploy:
- find hx_toolkit/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > hx_toolkit/VERSION
deploy:
  provider: pypitest
  user: uw-it-axdd
  skip_cleanup: true
  password:
    secure: X13UIAmiPRmr0furxG8jErrzww8snWbjVP3GfR+d5tfPBPi+BjRbVQHDGavF2SkTft7kBjcV6yx1bv6bmlLZSWTGod8I7xo/Ks/5xEfbE+cLZk5Z6AC+9yt90+41c4ZRyMtkhH2nX1kv6bgbFDwtatxga/gKlzKNbhLnXwxgajuTuz9uKMKxBtcRDgB71GLzhcKKuiwBSLKEDozcjhgLA46y53E4CVnXU4Czt/BWleSJRh6OOvfg9Ty8qRYA1fIg0cTOejWUHl/WV+nelUjms6RDHc91VnO2XAZeEurRrDlMHjken2QtAEjAe4qna55hG7HzCoAlaOzd2QHkgIGzb7nxz1DrmlkS07VxcbhpBevfvETixA2KGlufvBCh5JMK7jpsbVNu62HtCzC7AzeN/OIgw2J9/T0mVc1R7fv7+J0ukJYEQnnzpNqoig960hpnS/TmBSNSXZnqgj1AHwC0QM1i9XDbNe4WkaFPMkOnLkdH3EtQ4bXkuruGNS+3VEjF1yytMgpqDkjAQoBihq1ov5DSNCEuL4kbB+03sgBwQV9R39kVQ4rb2FJMyk16t9XlYIqcf0qSfALqVe5pXkl5dhNme0bEv2/2Grf/7+lqwu1XsNtlkdzX/R4Fps6Nuq4XqjkWyx/AHglKo7ekL0VZtN2uA9BPUjY0uWe5IKUi5do=
  on:
    tags: true
    python: '2.7'
