ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    interview-db.axdd:
      host: interview-db.axdd.s.uw.edu
      paths: 
        - "/"
database:
  engine: mysql
  name: interview_test
  hostname: interview-db-db-service
  secretName: interview-db.axdd.s.uw.edu-db
externalService:
  enabled: true
  name: interview-db-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.14 
  servicePort: 3306
repo: interview-db
instance: test
targetAverageUtilization: 90
resources:
  limits:
    cpu: 600m
  requests:
    cpu: 200m
image:
  repository: registry.hub.docker.com/acait/interview-db
  tag: IMAGE_TAG
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
environmentVariables:
  - name: ENV
    value: dev
  - name: AUTH
    value: SAML_DJANGO_LOGIN
  - name: ID_ADMIN_GROUP
    value: u_jcivjan_sip-admin
  - name: ID_FRONT_END_GROUP
    value: u_jcivjan_sip-frontend
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: interview-db.axdd.s.uw.edu-secrets
    secretKey: django-secret
