ingress:
  enabled: true
  tls:
    notify:
      secretName: interview-db.axdd.s.uw.edu-ingress-cert
      hosts:
        - interview-db.axdd.s.uw.edu
  hosts:
    interview-db.axdd:
      host: interview-db.axdd.s.uw.edu
      paths: 
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
database:
  engine: mysql
  name: interview_test
  hostname: interview-db-db-service
  secretName: interview-db.axdd.s.uw.edu-db
externalService:
  enabled: true
  name: interview-db-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.14 
  servicePort: 3306
repo: interview-db
instance: test
targetAverageUtilization: 90
resources:
  limits:
    cpu: 600m
  requests:
    cpu: 200m
image:
  repository: registry.hub.docker.com/acait/interview-db
  tag: IMAGE_TAG
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
environmentVariables:
  - name: ENV
    value: dev
  - name: AUTH
    value: SAML
  - name: ID_ADMIN_GROUP
    value: u_jcivjan_sip-admin
  - name: ID_FRONT_END_GROUP
    value: u_jcivjan_sip-frontend
  - name: SAML_ENTITY_ID
    value: https://interview-db.axdd.s.uw.edu/saml2
  - name: CLUSTER_CNAME
    value: interview-db.axdd.s.uw.edu
  - name: SAML_USER_ATTRIBUTE
    value: eppn
  - name: SP_CERT
    value: 'MIIHCzCCBfOgAwIBAgIRAKmh/IiI7pGHfMlkUnoqu54wDQYJKoZIhvcNAQELBQAwdjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk1JMRIwEAYDVQQHEwlBbm4gQXJib3IxEjAQBgNVBAoTCUludGVybmV0MjERMA8GA1UECxMISW5Db21tb24xHzAdBgNVBAMTFkluQ29tbW9uIFJTQSBTZXJ2ZXIgQ0EwHhcNMjAwNjE5MDAwMDAwWhcNMjIwNjE5MjM1OTU5WjCBtzELMAkGA1UEBhMCVVMxDjAMBgNVBBETBTk4MTk1MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdTZWF0dGxlMRkwFwYDVQQJExA0NTQ1IDE1dGggQXZlIE5FMSEwHwYDVQQKExhVbml2ZXJzaXR5IG9mIFdhc2hpbmd0b24xDjAMBgNVBAsTBVVXLUlUMSMwIQYDVQQDExppbnRlcnZpZXctZGIuYXhkZC5zLnV3LmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALHj5vKeLT9hifM/otq6fdTz0s3KBLruE6OSDBJbAuIhOuNjMauDMUluRgQ7Aih7zAkzMb/v7A2S5hpiWLNQb8nYc4mO8Vodh3NS8yzUxxT+PCcBE6a1G6zI0IWC1OEMC40O0oFZ2LX3GiIks0h2e9WsBL09QU0ALzhLbPB0rj6zUWzlW6sxABiHG+QFpfqreyQTo5ehc18ExzlM63FtJsZs74WGrlPoezYfOQB3UOiAW1/sn2ZEbkQvxcHY0XMxyht73XrqsUjEku+nqZfEEtymIo4AWHWACkNkoVhk2xfTNBWaR14EytSdjm4uKjpz0Ccxqge4IgqukZrltGoFv3cCAwEAAaOCA1AwggNMMB8GA1UdIwQYMBaAFB4Fo3ePbJbiW4dLprSGrHEADOc4MB0GA1UdDgQWBBTTU+oie1qyDVnWfH/N7TlghaWUMzAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwZwYDVR0gBGAwXjBSBgwrBgEEAa4jAQQDAQEwQjBABggrBgEFBQcCARY0aHR0cHM6Ly93d3cuaW5jb21tb24ub3JnL2NlcnQvcmVwb3NpdG9yeS9jcHNfc3NsLnBkZjAIBgZngQwBAgIwRAYDVR0fBD0wOzA5oDegNYYzaHR0cDovL2NybC5pbmNvbW1vbi1yc2Eub3JnL0luQ29tbW9uUlNBU2VydmVyQ0EuY3JsMHUGCCsGAQUFBwEBBGkwZzA+BggrBgEFBQcwAoYyaHR0cDovL2NydC51c2VydHJ1c3QuY29tL0luQ29tbW9uUlNBU2VydmVyQ0FfMi5jcnQwJQYIKwYBBQUHMAGGGWh0dHA6Ly9vY3NwLnVzZXJ0cnVzdC5jb20wJQYDVR0RBB4wHIIaaW50ZXJ2aWV3LWRiLmF4ZGQucy51dy5lZHUwggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoBaAB2AEalVet1+pEgMLWiiWn0830RLEF0vv1JuIWr8vxw/m1HAAABcs6HMOIAAAQDAEcwRQIhAPdhbnBvuCGowRL/FV1hPfTWPXEwC1yYFwHVfw1KeKwxAiBZG5uDYIge3oY3kSlnDDWi/eBI0HfL8rpvUflJHpMEAgB2AN+lXqtogk8fbK3uuF9OPlrqzaISpGpejjsSwCBEXCpzAAABcs6HMQoAAAQDAEcwRQIhAIOwBmn2VBA7vrTOp2sqn+W7cYtftsfs3msC0mtomVRUAiBHGiJ50RRQdCqwcxYXqdQIp81P/s/8ctJdY5qvIlSCiAB2AG9Tdqwx8DEZ2JkApFEV/3cVHBHZAsEAKQaNsgiaN9kTAAABcs6HMNsAAAQDAEcwRQIhAO1PPi/7yAMmFxOK70tmcehBWqKj8P2m+hP3+Uv0sqIEAiBNDigIiEvDHykGKdmViU1KDbcsU2sZFa/3r1QgNtM/szANBgkqhkiG9w0BAQsFAAOCAQEAJo8lsOhev+VWCG3or1ysx3L33zjxSG/Q3/SQ9zprV5KARLulJ4nlyexrc/RL4QmCW+MzMbh7EiDQ1cgVLyjJXr2i9qLVWGu/uKYMddpuS5jOPDIPEdI2XgQjCMmXM9MH8CXm7Ap05tczGa+9rDH1f6zbQPFdAczg2S+gCkpSbm09cFTP/MCWFHILFm66N1Xj6X4AQo+hbaUVTm4DOlMlHojcvlI6cJgUjBy0kufBdDfypKBjggDA+CzsSYL5RAqcNl+qEGir/dNV0XboNYj6HiF8HSRruOroyXJcZKpTvOQDgmI2CJSITlaOCzBQQ5fzbhw5wOQhGWh2XiORx4cpOQ=='
  - name: IDP_CERT
    value: 'MIID/TCCAuWgAwIBAgIJAMoYJbDt9lKKMA0GCSqGSIb3DQEBBQUAMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTAeFw0xMTA0MjYxOTEwMzlaFw0yMTA0MjMxOTEwMzlaMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMH9G8m68L0Hf9bmf4/7c+ERxgDQrbq50NfSi2YTQWc1veUIPYbZy1agSNuc4dwn3RtC0uOQbdNTYUAiVTcYgaYceJVB7syWf9QyGIrglZPMu98c5hWb7vqwvs6d3s2Sm7tBib2v6xQDDiZ4KJxpdAvsoPQlmGdgpFfmAsiYrnYFXLTHgbgCc/YhV8lubTakUdI3bMYWfh9dkj+DVGUmt2gLtQUzbuH8EU44vnXgrQYSXNQkmRcyoE3rj4Rhhbu/p5D3P+nuOukLYFOLRaNeiiGyTu3P7gtc/dy/UjUrf+pH75UUU7Lb369dGEfZwvVtITXsdyp0pBfun4CP808H9N0CAwEAAaOBwTCBvjAdBgNVHQ4EFgQUP5smx3ZYKODMkDglkTbduvLcGYAwgY4GA1UdIwSBhjCBg4AUP5smx3ZYKODMkDglkTbduvLcGYChYKReMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdYIJAMoYJbDt9lKKMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAEo7c2CNHEI+Fvz5DhwumU+WHXqwSOK47MxXwNJVpFQ9GPR2ZGDAq6hzLJLAVWcY4kB3ECDkRtysAWSFHm1roOU7xsU9f0C17QokoXfLNC0d7KoivPM6ctl8aRftU5moyFJkkJX3qSExXrl053uxTOQVPms4ypkYv1A/FBZWgSC8eNoYnBnv1Mhy4m8bfeEN7qT9rFoxh4cVjMH1Ykq7JWyFXLEB4ifzH4KHyplt5Ryv61eh6J1YPFa2RurVTyGpHJZeOLUIBvJu15GzcexuDDXe0kg7sHD6PbK0xzEF/QeXP/hXzMxR9kQXB/IR/b2k4ien+EM3eY/ueBcTZ95dgVM='
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: interview-db.axdd.s.uw.edu-secrets
    secretKey: django-secret
