ingress:
  enabled: true
  tls:
    notify:
      secretName: interview-db.axdd.s.uw.edu-ingress-cert
      hosts:
        - interview-db.axdd.s.uw.edu
  hosts:
    interview-db.axdd:
      host: interview-db.axdd.s.uw.edu
      paths: 
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
database:
  engine: mysql
  name: interview_test
  hostname: interview-db-db-service
  secretName: interview-db.axdd.s.uw.edu-db
externalService:
  enabled: true
  name: interview-db-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.14 
  servicePort: 3306
repo: interview-db
instance: test
targetAverageUtilization: 90
resources:
  limits:
    cpu: 600m
  requests:
    cpu: 200m
image:
  repository: registry.hub.docker.com/acait/interview-db
  tag: IMAGE_TAG
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
environmentVariables:
  - name: ENV
    value: dev
  - name: AUTH
    value: SAML
  - name: ID_ADMIN_GROUP
    value: u_jcivjan_sip-admin
  - name: ID_FRONT_END_GROUP
    value: u_jcivjan_sip-frontend
  - name: SAML_ENTITY_ID
    value: https://interview-db.axdd.s.uw.edu/saml2
  - name: CLUSTER_CNAME
    value: interview-db.axdd.s.uw.edu
  - name: SAML_USER_ATTRIBUTE
    value: eppn
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: interview-db.axdd.s.uw.edu-secrets
    secretKey: django-secret
  samlSpCertSecret:
    name: SP_CERT
    secretName: interview-db.axdd.s.uw.edu-saml-cert
    secretKey: sp-cert
  samlIdpCertSecret:
    name: IDP_CERT
    secretName: interview-db.axdd.s.uw.edu-saml-cert
    secretKey: idp-cert